microsoft/FHIR-Analytics-Pipelines

azure-pipelines.yml

Update CI pipeline:
- Update trigger to main and synapse branch
- Update version to 0.3.0
- Update NuGet feed to the one in microsofthealthoss
- Add GitHub release task

Update CI pipeline

---

deploy/templates/FhirSynapsePipelineTemplate.json

Update package url to a public accessable build package.

Update package link

---

FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Scheduler/Jobs/AzureBlobJobStore.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Scheduler/Jobs/JobManager.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Scheduler.UnitTests/Jobs/InMemoryJobStoreTests.cs

Add support to resume failed jobs.

Add support to resume failed jobs

---

FhirToDataLake/docs/Data-Mapping.md

Fix some format and typos

---

FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json

Fix error message when deploying Synapse Sync pipeline.
Seems deploying appInsights need obvious agreement, rather than ```You will need to Agree to the terms of service below to create this resource successfully.``` will appear.
Fixed:

Fix error messgae when deploy

---

azure-pipelines.yml

Fix emulator setup in azure pipeline (#96)

---

FhirToCdm/docs/fhir-to-cdm.md

1. Fix invalid links in the document.
2. Add simple guidance for FhirToCdm local tool.

Fix invalid link and add tool guidence

---

FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json

add filter configuration in the template

add filter configuration in template

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Microsoft.Health.Fhir.Synapse.Common.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Microsoft.Health.Fhir.Synapse.SchemaManagement.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Parquet/FhirParquetSchemaConstants.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Parquet/SchemaProvider/AcrCustomizedSchemaProvider.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Parquet/SchemaProvider/JsonSchemaParser.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.SchemaManagement.UnitTests/Microsoft.Health.Fhir.Synapse.SchemaManagement.UnitTests.csproj
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.SchemaManagement.UnitTests/Parquet/SchemaProvider/AcrCustomizedSchemaProviderTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.SchemaManagement.UnitTests/Parquet/SchemaProvider/JsonSchemaParserTests.cs

Update json schema lib to NJsonSchema.
Also update the reference FHIR-Converter version

Update the json schema lib

---

FhirToCdm/Configuration-Generator/test/publishConfigurations.test.js
FhirToCdm/build.yml

The FhirToCdm unit tests sometime fail in ci pipeline, update the check condition and pipeline script for them.

Fix Cdm unit tests in ci pipeline

---

azure-pipelines.yml

Bump version from 0.3.0 to 0.4.0 for filtering release

bump version to 0.4.0 for filtering release

---

FhirToDataLake/docs/Deployment.md

Correct the doc link for filtering.

Correct the doc link for filtering

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationConstants.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/StorageConfiguration.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Extensions/ConfigurationRegistrationExtensions.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Microsoft.Health.Fhir.Synapse.Core.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataWriter/Azure/AzureBlobContainerClientFactory.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataWriter/Azure/IAzureBlobContainerClientFactory.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/appsettings.json
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/appsettings.json
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Tasks/TaskExecutorTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.DataWriter.UnitTests/DataWriterTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Parquet.HealthCheck.UnitTests/MockAzureBlobContainerClientFactory.cs

Will use connection string to create blob container if connection string is given in configuration.

add connection string

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataFilter/GroupMemberExtractor.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/FhirToDataLakeOrchestratorJob.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/DataFilter/GroupMemberExtractorTests.cs

Remove the resource content in logs.

Remove the resource content in logs

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Microsoft.Health.Fhir.Synapse.Common.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataProcessor/DataConverter/CustomSchemaConverter.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Microsoft.Health.Fhir.Synapse.SchemaManagement.csproj

Convet the **JObject** to improve prefermance.

Convert JObject

---

FhirToDataLake/azurepipelines/pack-nugets.yml
azure-pipelines.yml

Pack Nugets in release stage.
Have create the release pipeline to push the Nuget packages to FhirAnalytics feed.

Pack nugets

---

FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/JobConfiguration.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Extensions/ServiceCollectionExtensions.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/AzureTableMetadataStore.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/FhirToDataLakeProcessingJob.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/TableKeyProvider.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/appsettings.json
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.JobManagement/AzureStorageClientFactory.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.JobManagement/AzureStorageJobQueueClient.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.JobManagement/AzureStorageKeyProvider.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/appsettings.json
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Common.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/AzureTableMetadataStoreTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/FhirToDataLakeOrchestratorJobTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/SchedulerServiceTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/E2ETests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/appsettings.test.json
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.JobManagement.UnitTests/AzureStorageJobQueueClientTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Parquet.HealthCheck.UnitTests/Checkers/SchedulerServiceHealthCheckerTests.cs

- Remove **agentName** config
- Add Table and Queue names for internal job and metadata.

Update agentName to Queue and Table name

---

FhirToDataLake/scripts/Set-SynapseEnvironment.ps1

1. Update job to retry if failed
2. Use **sasToken** rather than **connectedAccount** to create storage context.

Fix create place holder blob failed bug

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationValidators/ConfigurationValidatorV1.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/FilterLocation.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataFilter/ContainerRegistryFilterProvider.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/appsettings.json
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/appsettings.json

Update ACR Filter Config

---

FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json

Update function settings since Azure Function runtime version will no longer be supported by December 3, 2022.

Update function template

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataFilter/ContainerRegistryFilterProvider.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/Api/FhirApiDataClient.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/ContainerRegistry/ContainerRegistryAccessTokenProvider.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Parquet/SchemaProvider/AcrCustomizedSchemaProvider.cs

Fix incorrect placeholder in **string.Format()**

Fix incorrent placeholder in string format

---

FhirToDataLake/azurepipelines/ci.yml
FhirToDataLake/deploy/templates/DeployAzureFunction.json
FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/JobManagerFunction.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/Microsoft.Health.Fhir.Synapse.FunctionApp.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/Program.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/host.json
publish.yml

1. Update ci pipeline to enable Azure Function
2. Update Arm template to deploy Linux Azure Function according to examples [here](https://github.com/azure-samples/function-app-arm-templates/tree/main/zip-deploy-run-from-package). For completed sample, see [link](https://github.com/Azure-Samples/function-app-arm-templates/tree/main/function-app-premium-plan).

Deploy Linux Azure Function

---

FhirToDataLake/scripts/Set-SynapseEnvironment.ps1

To avoid the script using old schema files. use image digest as suffix for customized schema directory.

Use Digest As Suffix For Customized Schema Directory

---

azure-pipelines.yml

Bump CI version to 0.6.0

---

FhirToDataLake/deploy/templates/ContainerApp/DeployDicomPipelineToContainerApp.json
FhirToDataLake/deploy/templates/ContainerApp/DeployFhirPipelineToContainerApp.json
FhirToDataLake/deploy/templates/Function/DeployFhirPipelineToFunction.json
FhirToDataLake/scripts/Set-SynapseEnvironment.ps1

The 0.6.0 image is ready
Update default deployment to 0.6.0

Update default deployment to 0.6.0

---

FhirToCdm/Microsoft.CommonDataModel.ObjectModel.Adapter.Adls/Microsoft.CommonDataModel.ObjectModel.Adapter.Adls.csproj
FhirToCdm/Microsoft.CommonDataModel.ObjectModel/Microsoft.CommonDataModel.ObjectModel.csproj
FhirToCdm/Microsoft.Health.Fhir.Transformation.Cdm.Test/Microsoft.Health.Fhir.Transformation.Cdm.Test.csproj
FhirToCdm/Microsoft.Health.Fhir.Transformation.Core/Microsoft.Health.Fhir.Transformation.Core.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Microsoft.Health.Fhir.Synapse.Common.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Microsoft.Health.Fhir.Synapse.Core.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Microsoft.Health.Fhir.Synapse.SchemaManagement.csproj
publish.yml

Solve the restore errors in auto-generated PR.

Bump Newtonsoft.Json To 13.0.2

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationResolvers/BaseConfigurationResolver.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationResolvers/ConfigurationResolverV2.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationValidators/ConfigurationValidator.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/SupportedConfigVersion.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Extensions/ConfigurationRegistrationExtensions.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/Microsoft.Health.Fhir.Synapse.Tool.csproj
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/appsettings-example-v1.json
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Common.UnitTests/Extensions/ConfigurationRegistrationExtensionsTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/FhirToDataLakeE2ETests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/appsettings.dicomtodatalake.test.json
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/appsettings.fhirtodatalake.test.json

Update ConfigVersion 2 for DICOM data source.
The ConfigVersion only support FHIR as data source, and ConfigVersion 2 support FHIR or DICOM.

Update ConfigVersion 2 For Different Data Source

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.HealthCheck/Checkers/AzureBlobStorageHealthChecker.cs

Currently we keep a container client in health check and reuse the client, which can lead to problem when user drops the permission and health check still reports healthy.

Avoid reusing container client in blob health check

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/JobVersionManager.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/Models/FhirToDataLakeAzureStorageJobInfo.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/Models/FhirToDataLakeJobInputDataProperties.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/AzureStorageJobFactoryTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/FhirToDataLakeAzureStorageJobInfoTests.cs

Generate job identifiers by selecting specified fields for different job versions.

generate job identifier by selecting fields for different job versions

---

FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/DicomSchedulerServiceTests.cs

The Dicom Scheduler Service may haven't re-new entity in raw delay.

Extend delay for DicomSchedulerService ut

---

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Metrics/HealthStatusMetric.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Metrics/MetricNames.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Metrics/ProcessLatencyMetric.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Metrics/ResourceLatencyMetric.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Metrics/SuccessfulDataSizeMetric.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Metrics/SuccessfulResourceCountMetric.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Metrics/TotalErrorsMetric.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Extensions/MetricsLoggerExtensions.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/DicomToDataLakeOrchestratorJob.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/FhirToDataLakeOrchestratorJob.cs
FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.HealthCheck/HealthCheckBackgroundService.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/DicomToDataLakeOrchestratorJobTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/DicomToDataLakeProcessingJobTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/FhirToDataLakeOrchestratorJobTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/FhirToDataLakeProcessingJobTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/MockMetricsLogger.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/SchedulerServiceTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Parquet.HealthCheck.UnitTests/HealthCheckBackGroundServiceTests.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Parquet.HealthCheck.UnitTests/MockBrokenHealthCheckListener.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Parquet.HealthCheck.UnitTests/MockHealthCheckListener.cs
FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Parquet.HealthCheck.UnitTests/MockHealthCheckMetricsLogger.cs

1. Fix bug in log error metrics.
2. Add tests for metrics.

Fix Bug In Error Metrics

---

FhirToDataLake/deploy/templates/ContainerApp/DeployDicomPipelineToContainerApp.json
FhirToDataLake/deploy/templates/ContainerApp/DeployFhirPipelineToContainerApp.json

The deploy for dicom-to-datalake will fail in initialization stage.

Add configVersion to ARM templates

---

FhirToDataLake/deploy/templates/ContainerApp/DeployDicomPipelineToContainerApp.json
FhirToDataLake/deploy/templates/ContainerApp/DeployFhirPipelineToContainerApp.json
FhirToDataLake/deploy/templates/Function/DeployFhirPipelineToFunction.json
FhirToDataLake/scripts/Set-SynapseEnvironment.ps1
azure-pipelines.yml

1. Update version to **v0.6.2**
2. The tag of the image been pushed by release pipeline is **0.6.2.1**

Update version to 0.6.2
