microsoft/FHIR-Analytics-Pipelines

FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.DataSerialization.UnitTests/Parquet/ParquetDataProcessorTests.cs
Previously the large data test takes too much time in pipeline which causes the pipeline to time out. By investigation, this is because of `List.AddRange`, which gets slower over times and costs too much memory. Change it to `Enumerable.Repeat` solves the problem.
=> Refine large data test

FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/E2ETests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/appsettings.test.json
Refine mock FHIR Server and E2E tests from FHIR Server to Storage to be aligned with real Azure FunctionApp trigger, which is needed by E2E tests from FHIR Server to Synapse.
=> Refine E2E tests

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/JobManagerFunction.cs
Disable function time trigger RunOnStartup,
RunOnStartup=True may leading code execute at highly unpredictable times. See https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#configuration
=> Disable function RunOnStartup

FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json
Hierarchical namespace is not enabled by default in storage v2 deployment.
We need to specify the option explicitly in the arm template.
=> Enable hierarchical namespace in storage v2 template

FhirToDataLake/docs/Deployment.md
In [deployment](https://github.com/microsoft/FHIR-Analytics-Pipelines/blob/main/FhirToDataLake/docs/Deployment.md) page, **Deploy to Azure** button is crush from my side due to the security certificate error, the newest document [Deploy on github](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button) recommends to use **https://aka.ms/deploytoazurebutton** as the button image.
=> Update Deploy to Azure button image

azure-pipelines.yml
Add conditions in azure pipeline ```Release``` stage.
Multiple jobs may been built in parallel if set up multiple agents, see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#dependencies
=> Conditions in Release stage

FhirToDataLake/NuGet.Config
The `NuGet.Config` file currently references a private nuget source, which will raise authorization errors when restoring packages. Now we change to a public NuGet source.
=> Fix private NuGet source

FhirToDataLake/synapse-e2e-test.yml
Add ```-Force``` when upload package to storage in synapse-e2e-test pipeline.
Currently if job failed but has already uploaded zip package to storage, re-try will always fail because ```Set-AzStorageBlobContent``` command need to confirm whether to overwrite exist blob, but pipeline is not run in interactive mod.
=> Force upload package in devOps pipeline

FhirToDataLake/NuGet.Config
We should add the public nuget source to nuget.conf explicitly as upstream sources are not supported for public feeds. [Reference](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#best-practices-feed-ownerspackage-publishers)
=> Add nuget public source

FhirToDataLake/global.json
Currently we may face local build issues when having a newer SDK than the one included in Visual Studio for C++/CLI projects, specifying the .NET SDK version will help mitigate the issue.
=> Add global.json

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/Api/FhirApiDataClient.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/Api/FhirApiDataSource.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.DataClient.UnitTests/Api/FhirApiDataClientTests.cs
If the base FHIR server [Uri](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-6.0) has relative parts and the relative part does not end with a trailing slash  (like /api) , then the relative part will be omitted when composing a FHIR search uri. In this pull request, we always append a trailing slash to the FHIR base uri if the trailing slash is not present.
=> Fix FHIR server URL missing trailing slash issue

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataWriter/Microsoft.Health.Fhir.Synapse.DataWriter.csproj
Currently the referenced data lake client may convert dfs and blob endpoints incorrectly, which can break the pipeline when committing the staged data. Update the library version to fix the unexpected behavior.
For more details, see the [pull request link](https://github.com/Azure/azure-sdk-for-net/commit/8406d81100e9ba3b171fdf9d08896756e1e4132a).
=> Fix data lake client error when parsing data lake storage endpoints.

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Models/Data/BatchDataResult.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Models/Data/StreamBatchData.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Models/Jobs/Job.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Models/Tasks/TaskContext.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Models/Tasks/TaskResult.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataProcessor/IColumnDataProcessor.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataProcessor/ParquetDataProcessor.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataProcessor/ProcessParameters.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/AzureBlobJobStore.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/JobExecutor.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/JobManager.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/JobProgressUpdater.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Microsoft.Health.Fhir.Synapse.Core.csproj, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Tasks/TaskExecutor.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataWriter/Azure/AzureBlobDataWriter.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataWriter/IFhirDataWriter.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/IFhirSchemaManager.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Parquet/FhirParquetSchemaManager.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/DataProcessor/ParquetDataProcessorTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/InMemoryJobManagerTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/InMemoryJobStoreTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/JobProgressUpdaterTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Tasks/TaskExecutorTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/TestData/Schemas/Observation.json, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/TestData/Schemas/Patient.json, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/TestData/Schemas/Patient_customized.json, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/TestUtils.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.DataWriter.UnitTests/DataWriterTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.SchemaManagement.UnitTests/Parquet/FhirParquetSchemaManagerTests.cs
Add schema types to Job and Task context, so that pipeline can generate multiple output parquet sets for one resource type.
Temporarily, there is only one schema type be set to each resource type inside the engine, the user interface has no changes.
=> Add target schema types in Job and Task context

FhirToCdm/Microsoft.CommonDataModel.ObjectModel.Adapter.Adls/Microsoft.CommonDataModel.ObjectModel.Adapter.Adls.csproj, FhirToCdm/Microsoft.CommonDataModel.ObjectModel/Microsoft.CommonDataModel.ObjectModel.csproj, FhirToCdm/Microsoft.Health.Fhir.Transformation.Cdm.Test/Microsoft.Health.Fhir.Transformation.Cdm.Test.csproj, FhirToCdm/Microsoft.Health.Fhir.Transformation.Core/Microsoft.Health.Fhir.Transformation.Core.csproj
Combine the robot PRs to upgrade Newtonsoft version.
The pipeline tests failed for individual updates due to dependency issue.
=> Upgrade newtonsoft.json 13.0.1

FhirToDataLake/build.yml, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.SchemaManagement.UnitTests/ContainerRegistry/ContainerRegistryTemplateProviderTests.cs
The **DefaultAzureCredential** will try to get the following credential types in order:
[EnvironmentCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet)
[ManagedIdentityCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet)
[SharedTokenCacheCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.sharedtokencachecredential?view=azure-dotnet)
[VisualStudioCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocredential?view=azure-dotnet)
[VisualStudioCodeCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocodecredential?view=azure-dotnet)
[AzureCliCredential](https://docs.microsoft.com/en-us/dotnet/a …
=> Set up service principal as environment credential

FhirToDataLake/build.yml, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/Microsoft.Health.Fhir.Synapse.E2ETests.csproj
To work around the authentication issue from [**AzureServiceTokenProvider**](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#using-the-library), use AzureCLI task to run the E2E test in DevOps ci pipeline.
=> DepOps pipeline uses AzureCLI task to run E2ETests

FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.DataWriter.UnitTests/Azure/AzureBlobContainerClientTests.cs
I find a unit test will try to use same stream to test an interface ```CreateBlobAsync(string blobName, Stream stream, CancellationToken cancellationToken = default)```, which may lead to thread issue.
```
stream.Seek(0, SeekOrigin.Begin);
try
{
await blobClient.UploadAsync(stream, cancellationToken);
_logger.LogInformation("Created blob '{0}' successfully.", blobName);
return true;
}
```
=> Fix AzureBlobContainerTests using same stream

FhirToDataLake/deploy/templates/FhirSynapsePipelineTemplate.json
Currently we use classic Application Insights to collect the logs, Refer the [Create Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-new-resource) document, the newer regions introduced after February 2021 do not support creating classic Application Insights resources.
Add appInsightsLocation parameter in deploy ARM template, its value be restricted on some available regions, same with [deploy template](https://github.com/microsoft/fhir-server/blob/main/samples/templates/default-azuredeploy.json#L87) of fhir-server.
=> Specifices the Application Insights location

FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/DataProcessor/ParquetDataProcessorTests.cs
Current unit test will trigger an out of memory error.
The DevOps pipeline default agents that run Windows are provisioned on Azure general purpose virtual machines with 7 GB of RAM refer to [Hardware](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware), and our unit test take 7 GB memory in my local test.
=> Set the data repeat count to 50 in unit test

FhirToDataLake/synapse-e2e-test.yml
Update to try clear the test database in ci pipeline.
The Synapse SQL pool sometimes reject the drop database command because the database still in use.
The e2e test is passed and we can still publish the package rather than manually reset the environment and try.
=> Update to try clear the test database

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationConstants.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationResolvers/ConfigurationResolverV1.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationValidators/ConfigurationValidatorV1.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/ConfigurationValidators/ValidateUtility.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/SupportedConfigVersion.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Extensions/ConfigurationRegistrationExtensions.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/appsettings.json, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/appsettings.json, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Common.UnitTests/Configurations/ConfigurationValidators/ValidatorUtilityTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Common.UnitTests/Extensions/ConfigurationRegistrationExtensionsTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/appsettings.test.json
Add config versioning strategy for future compatibility.
When we need to embrace new version of configurations, a common strategy should be bump the config version and add corresponding config resolver and validator if needed. By the way, we may need to have different versions for XXXConfiguration objects in case of property conflicts  in the future.
=> Add config versioning

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Models/Jobs/Job.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/JobExecutor.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/JobProgressUpdater.cs
This pr is to fix the bug that the job may hang when trying to update job progress.
Channel is used to update job progress when a task is completed, the completed task will be removed from the job's runningTasks, it's async and may hang as Dictionary is not thread-safe. Use `concurrencyDictionay`  for runningTasks to fix this issue.
=> [bugfix] The job may hang when update job progress

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/Api/FhirApiConstants.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/Api/FhirApiDataClient.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.DataClient.UnitTests/Api/FhirApiDataClientTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/E2ETests.cs
`_sort` will bring latency issue when querying cosmos db backed FHIR server with large volumn of data. And removing sort will not cause changes to the data lake result.
=> Remove _sort search parameter

FhirToDataLake/deploy/templates/DeployContainer.json, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/JobConfiguration.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/appsettings.json, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/appsettings.json, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.E2ETests/appsettings.test.json
The default job concurrency may bring heavy CPU and memory pressure when the hosting machine is not very powerful. A lower single-node concurrency is also aligned with our target to scale out to multiple nodes in the future. So we currently decrease the default value and customer can set it during deployment template.
=> Decrease default job concurrency

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/Api/FhirApiDataClient.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/DataClientRegistrationExtensions.cs
1. Increase default circuit breaker limit, otherwise the circuit will break before retrying when calling apis in parallel.
2. Remove manual retries.
=> Fix data client

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Configurations/HealthCheckConfiguration.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Resource.Designer.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Common/Resource.resx, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataFilter/ContainerRegistryFilterProvider.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.DataClient/Api/FhirApiDataClient.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.FunctionApp/appsettings.json, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/ContainerRegistry/ContainerRegistryTemplateProvider.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Tool/appsettings.json
1. Change health check timeout from 60 to 100 seconds.
2. Refine message in FHIR server client to make health checker's log clearer.
=> Refine health check

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/SchedulerService.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.SchemaManagement/Parquet/FhirParquetSchemaManager.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/FhirToDataLakeAzureStorageJobInfoTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/SchedulerServiceTests.cs
When the scheduler service creates the next trigger, use the accelerated job end time which is the crontab scheduler occurrence time closest to the current time instead of next occurrence time.
=> accelerated job end time

GeoPol.xml
There are some sample data files that are defined by FHIR standard. These files are not sensitive and should not be scanned.
=> Exclude data files for scanning

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/DicomToDataLakeProcessingJob.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/DicomToDataLakeProcessingJobTests.cs
Keep the raw timeStamp strin value in DICOM Parquet data.
=> Keep Raw TimeStamp String In DICOM Parquet

FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/DataProcessor/ParquetDataProcessor.cs, FhirToDataLake/src/Microsoft.Health.Fhir.Synapse.Core/Jobs/DicomToDataLakeProcessingJob.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/DataProcessor/ParquetDataProcessorTests.cs, FhirToDataLake/test/Microsoft.Health.Fhir.Synapse.Core.UnitTests/Jobs/DicomToDataLakeProcessingJobTests.cs
1. Handle empty invalid change feed, which means all change feeds are replaced or deleted.
2. Add tests for that.
=> Handle empty invalid change feed

publish.yml
The FhirToDatalake image and function app artifacts are uploaded to CI as pipeline artifacts, we should use **DownloadPipelineArtifact** to download them in _publish_ stage.
=> Fix CI Download Artifact Task

FhirToDataLake/azurepipelines/OverallTest/clean-environment.yml, FhirToDataLake/azurepipelines/OverallTest/dicomtosynapse-e2e-test.yml, FhirToDataLake/azurepipelines/OverallTest/fhirtosynapse-e2e-test.yml, azure-pipelines.yml
The FhirToDatalake overall test and DicomToDatalake overall test both will try to delete the test image after finishing, one of them may delete the test image when another overall test still need it.
Refine the CI logic, cleaning up the test image after DICOM and FHIR overall tests all finished.
=> Fix the image clean up dependency

FhirToDataLake/test/Microsoft.Health.AnalyticsConnector.Core.UnitTests/Jobs/DicomToDatalakeSchedulerServiceTests.cs, FhirToDataLake/test/Microsoft.Health.AnalyticsConnector.Core.UnitTests/Jobs/FhirToDatalakeSchedulerServiceTests.cs
Add delay in Dicom Schedular Server unit test as in CI, the server may not have enough time to finish the job.
=> Add Delay In Dicom Schedular Server Test

FhirToDataLake/synapse/FhirToSynapseValidator.py
Omit primitive extension when compareing columns in CI overall test.
=> Omit primitive extension when compareing columns
